---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${UI_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: PROD
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to prod
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      # Start the load
      # export APP_URL=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      # curl "${APP_URL}/autoLoadTest.php?count=100&delay=0&action=start"
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
